# Generated by Django 5.2.5 on 2025-12-12 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('abeka', 'Abeka'), ('tesano', 'Tesano'), ('lapaz', 'Lapaz'), ('aladjo', 'Aladjo')], default='none', max_length=50)),
                ('capacity', models.IntegerField()),
                ('available_rooms', models.IntegerField()),
                ('price_for_one_in_a_room', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('price_for_two_in_a_room', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('price_for_three_in_a_room', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('price_for_four_in_a_room', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('contact', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('priceFilter', models.CharField(default='0.00', max_length=10)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('wifi', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('laundry', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('study_room', models.BooleanField(default=False)),
                ('common_lounge', models.BooleanField(default=False)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hostel_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HostelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hostel_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hostel.hostel')),
            ],
        ),
    ]
