# Generated by Django 5.2.5 on 2025-12-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='hostel_image',
            field=models.ImageField(blank=True, null=True, upload_to='hostel_image/'),
        ),
    ]
