# Generated by Django 5.2.5 on 2025-12-15 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='hostel',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to=settings.AUTH_USER_MODEL),
        ),
    ]
