# Generated by Django 5.2.5 on 2025-12-15 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_manager_address_alter_manager_whatsapp'),
        ('hostel', '0002_remove_hostel_image_remove_hostel_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to='accounts.manager'),
        ),
    ]
