# Generated by Django 5.2.5 on 2025-12-01 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_hostel_hostel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='hostel_image',
        ),
    ]
