# Generated by Django 5.2.5 on 2025-12-15 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_manager_user'),
        ('hostel', '0003_alter_hostel_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to='accounts.manager'),
        ),
    ]
