# Generated by Django 5.2.5 on 2025-12-01 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_remove_hostel_hostel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='report',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='report',
            name='name',
        ),
        migrations.DeleteModel(
            name='SystemSetting',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
