# Generated by Django 5.2.5 on 2025-12-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_alter_hostel_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='available_rooms',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='capacity',
        ),
        migrations.AlterField(
            model_name='hostel',
            name='location',
            field=models.CharField(choices=[('Abeka', 'Abeka'), ('Tesano', 'Tesano'), ('Tapaz', 'Lapaz'), ('Aladjo', 'Aladjo')], default='none', max_length=50),
        ),
    ]
