# Generated by Django 5.2.5 on 2025-12-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_remove_notification_user_remove_report_hostel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='locationFilter',
        ),
        migrations.AlterField(
            model_name='hostel',
            name='location',
            field=models.CharField(choices=[('abeka', 'Abeka'), ('tesano', 'Tesano'), ('lapaz', 'Lapaz'), ('aladjo', 'Aladjo')], default='none', max_length=50),
        ),
    ]
