# Generated by Django 5.2.5 on 2025-12-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_remove_hostel_locationfilter_alter_hostel_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='price',
        ),
        migrations.AddField(
            model_name='hostel',
            name='price_for_four_in_a_room',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
        migrations.AddField(
            model_name='hostel',
            name='price_for_one_in_a_room',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
        migrations.AddField(
            model_name='hostel',
            name='price_for_three_in_a_room',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
        migrations.AddField(
            model_name='hostel',
            name='price_for_two_in_a_room',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
    ]
