# Generated by Django 5.2.5 on 2025-12-15 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_remove_hostel_available_rooms_remove_hostel_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='contact',
        ),
    ]
