# Generated by Django 5.2.5 on 2025-12-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_remove_hostel_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
