# Generated by Django 5.2.5 on 2026-01-14 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_hostel_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='school',
        ),
    ]
