# Generated by Django 5.2.5 on 2026-01-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_remove_hostel_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='school',
            field=models.CharField(choices=[('KNUST', 'KNUST'), ('UG', 'UG'), ('GCTU', 'GCTU'), ('UPSA ', 'UPSA')], default='none', max_length=50),
        ),
    ]
