# Generated by Django 5.2.5 on 2025-12-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='address',
            field=models.TextField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
