# Generated by Django 5.2.5 on 2025-12-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_manager_address_alter_manager_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='address',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
