# Generated by Django 5.2.5 on 2026-01-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_passwordreset_token_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(default=22, max_length=255),
            preserve_default=False,
        ),
    ]
