# Generated by Django 5.2.5 on 2026-01-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_passwordreset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
