# Generated by Django 5.2.5 on 2026-01-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_passwordreset_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
