# Generated by Django 5.2.5 on 2026-01-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_passwordreset_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='email',
        ),
        migrations.RemoveField(
            model_name='passwordreset',
            name='token',
        ),
    ]
