# Generated by Django 5.2.5 on 2026-01-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_passwordreset_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(choices=[('GCTU', 'Ghana Communication Technology University'), ('UG', 'University of Ghana'), ('KNUST', 'Kwame Nkrumah University of Science and Technology'), ('UPSA ', 'University of Professional Studies Accra')], default='none', max_length=50),
        ),
    ]
