# Generated by Django 5.2.5 on 2026-01-30 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, choices=[('GCTU', 'Ghana Communication Technology University'), ('UG', 'University of Ghana'), ('KNUST', 'Kwame Nkrumah University of Science and Technology'), ('UPSA ', 'University of Professional Studies Accra')], max_length=50, null=True),
        ),
    ]
